[general]

[window]
blur = true
opacity = 0.7
class = { general = "alacritty" }
resize_increments = true
dimensions = { columns = 87, lines = 35 }
decorations_theme_variant = "Dark"

[font]
size=13
normal = { family = "FiraCode Nerd Font", style = "Retina" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block" }

[mouse]
hide_when_typing = true
