set -g default-shell /usr/bin/zsh

# No bells at all
set -g bell-action none

# Change the prefix key to alt-a
unbind C-b
set-option -g prefix M-b
bind M-b send-prefix

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

# improve colors
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# -----------------------------------------------statusline config
set -g status-left-length 20
set -g status-justify centre
set -g status-right "%H:%M"
set -g window-status-current-style "underscore"

set -g status-right '#[fg=colour166]#([ "$(tmux show-option -g prefix)" != "prefix C-a" ] && echo "($(tmux show-option -g prefix | cut -c 8-)) ")#[fg=colour33]%d %b %Y #{?client_prefix,#[fg=colour160],#[fg=colour61]}- #[fg=colour64]%H:%M #{?client_prefix,#[fg=colour160],#[fg=colour61]}- #[fg=colour37]#([ -f $HOME/.name ] && cat $HOME/.name || hostname)'
set -g status-left '#{?pane_input_off,#[fg=colour160],#[fg=colour136]}[#[fg=colour136]#S:#I.#P#{?pane_input_off,#[fg=colour160],#[fg=colour136]}] '

# statusline colors
set -g status-style bg=colour235,fg=colour136
setw -g window-status-style fg=colour244
setw -g window-status-current-style fg=colour166
setw -g window-status-activity-style fg=colour61
setw -g window-status-bell-style fg=colour61
set -g pane-border-style fg=colour4
set -g pane-active-border-style fg=colour2
set -g message-style bg=colour235,fg=colour166

# clock
setw -g clock-mode-colour colour64 #green
#------------------------------------------------

#-----------------------------------------------windows & panes
# pane number display
set -g display-panes-active-colour colour166 #blue
set -g display-panes-colour colour33 #orange

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# start window numbers at 1 to match keyboard order with tmux order
set -g base-index 1

# create new windows/panes in same directory
bind "\"" split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# pane navigation
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# window scrolling
bind -n M-] select-window -n
bind -n M-[ select-window -p
#------------------------------------------------
