#!/usr/bin/env bash

# w=$2 h=$3 x=$4 y=$5

t="$(mimetype -b "$1")"
icat="kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}""

case "$t" in
    *csv) csview "$1"; exit 1;;
    *text* | *json | *xml) bat -n --color=always "$1"; exit 1;;
    audio*) mediainfo "$1"; exit 1;;
    image*) $icat "$1" < /dev/null > /dev/tty; exit 1;;
    video*) $icat "$(vidthumb "$1")" < /dev/null > /dev/tty; exit 1;;
    *) pistol "$1"; exit 1;;
esac
