#!/usr/bin/env bash

# w=$2 h=$3 x=$4 y=$5

type="$(file -Lb --mime-type "$1")"
if [[ "$type" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}" "$1" < /dev/null > /dev/tty
    exit 1
elif [[ "$type" =~ ^video ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}" "$(vidthumb "$1")" < /dev/null > /dev/tty
    exit 1
fi

pistol "$1"
