#!/usr/bin/env bash

# w=$2 h=$3 x=$4 y=$5

t="$(mimetype -b "$1")"
icat="kitten icat --silent --stdin no --transfer-mode file --place "${2}x${3}@${4}x${5}""

if [[ "$t" =~ ^image ]]; then
    $icat "$1" < /dev/null > /dev/tty
    exit 1
elif [[ "$t" =~ ^video ]]; then
    $icat "$(vidthumb "$1")" < /dev/null > /dev/tty
    exit 1
fi

pistol "$1"
