#!/usr/bin/env bash

if ! [ -f "$1" ]; then
    exit 1
fi

cache="$HOME/.cache/vidthumb"
index="$cache/index.json"
video="$(realpath "$1")"

mkdir -p "$cache"

if [ -f "$index" ]; then
    thumbnail="$(jq -r ". \"$video\"" <"$index")"
    if [[ "$thumbnail" != "null" ]]; then
        if [[ ! -f "$cache/$thumbnail" ]]; then
            exit 1
        fi
        echo "$cache/$thumbnail"
        exit 0
    fi
fi

thumbnail="$(uuidgen).jpg"

if ! ffmpegthumbnailer -i "$video" -o "$cache/$thumbnail" -t 25% -s 0 2>/dev/null; then
    exit 1
fi

if [[ ! -f "$index" ]]; then
    echo "{\"$video\": \"$thumbnail\"}" >"$index"
fi
json="$(jq -r --arg "$video" "$thumbnail" ". + {\"$video\": \"$thumbnail\"}" <"$index")"
echo "$json" >"$index"

echo "$cache/$thumbnail"
