export PATH=$HOME/.local/bin:$PATH

export PLATFORM="$(uname)"
export TERMINAL="$(ps -p $PPID -o comm=)"
export OS_RELEASE="$(grep "^NAME" /etc/os-release | sed -E 's/^.*"(.*)"$/\1/')"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# ZSHCONFIG
export HISTSIZE=10000
export SAVEHIST=10000
export HIST_STAMPS="%d/%m/%y %T"
export HISTFILE="$HOME/.zsh_history"

# DOTFILES
export ZDOTDIR="$HOME/.zsh"
export ZSHRC="$HOME/.zsh/.zshrc"
export DOTDIR="$HOME/Documents/docs/dotfiles/mine"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripconf"

export EDITOR="nvim"
export BROWSER="firefox -private"
